version: '2'
services:
  app:
    container_name: k8s
    image: k8s
    build: ./
    ports:
      - "8083:8083"
    expose:
      - "8083"
    depends_on:
      - postgresqldb
  postgresqldb:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=k8sdb
