apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "k8schart.fullname" . }}
  labels:
    {{- include "k8schart.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "k8schart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "k8schart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          volumeMounts:
          - mountPath: "/var/lib/postgresql/data"
            name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-pv-claim 
    
                      